export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const FIREBASE_ERROR = 'FIREBASE_ERROR';
export const PASSWORD_RESET = 'PASSWORD_RESET';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const GET_PRODUCT_INFO = 'GET_PRODUCT_INFO';
export const GET_IMAGE = 'GET_IMAGE';

export const GET_PRODUCTS = 'GET_PRODUCTS';

export const GET_PACKAGES = 'GET_PACKAGES';
export const SET_USER_PACKAGE = 'SET_USER_PACKAGE';

export const SET_LOCAL_PACKAGE = 'SET_LOCAL_PACKAGE';
export const SET_BEER_PREFERENCES = 'SET_BEER_PREFERENCES';
export const LOAD_BEER_PREFERENCES = 'LOAD_BEER_PREFERENCES';
